apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: sti-camel-cdi
    name: sti-java-jboss-jdk8
  spec:
    dockerImageRepository: fabric8/sti-java-jboss-jdk8:1.0.6
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: sti-camel-cdi
    name: sti-camel-cdi
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: sti-camel-cdi
    name: sti-camel-cdi
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: sti-camel-cdi:latest
    resources: {}
    source:
      git:
        uri: https://github.com/rhuss/sti-camel-cdi.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: sti-java-jboss-jdk8:1.0.6
        forcePull: false
      type: Source
    triggers:
    - github:
        secret: oNSsoQZKLmq625YQzWu5
      type: GitHub
    - generic:
        secret: AVR6ZVYk-40vmUmFg7PF
      type: Generic
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: sti-camel-cdi
    name: sti-camel-cdi
  spec:
    replicas: 1
    selector:
      deploymentconfig: sti-camel-cdi
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: sti-camel-cdi
      spec:
        containers:
        - image: library/sti-camel-cdi:latest
          name: sti-camel-cdi
          ports:
          - containerPort: 8778
            protocol: TCP
          resources: {}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - sti-camel-cdi
        from:
          kind: ImageStreamTag
          name: sti-camel-cdi:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: sti-camel-cdi
    name: sti-camel-cdi
  spec:
    ports:
    - name: 8778-tcp
      nodePort: 0
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: sti-camel-cdi
  status:
    loadBalancer: {}
kind: List
metadata: {}
